<?php
return [
	
	'assignment_category' => [
		'CA',  
		'CS',  
		'CMA', 
		'Lawyer', 
		'MBA', 
		'Software Developer', 
		'Others'
	],
	'compliance_status1' => [
		'Updated upto',
		'Not Updated'
	],
	'compliance_status2' => [
		'Updated upto',
		'Not Updated',
		'Not Applicable'
	],
	'size_of_NBFC' => [
		'Systemically Important NBFCs',
		'Non‐Systemically Important NBFCs', 
		'Not Applicable',
	],
	'type_of_NBFC' => [
		'Asset Finance Company', 
	   'Investment and Credit Company',
		'Micro Finance Institution', 
	  'Infrastructure Finance Company',
		'Systemically Important Core Investment Company', 
		'Infrastructure Debt Fund', 
		'Factor', 
		'Mortgage Guarantee Company', 
		'Account Aggregator',
		'Peer‐to‐Peer Lending Platform', 
		'Housing Finance Companies', 
		'Core Investment Companies', 
		'Gold Loan NBFC', 
		'Residuary NBFC', 
		'Others',
	],
	'NBFC_company' => [
		'LISTED NBFC (NSE MAIN BOARD)',
		'LISTED NBFC (BSE MAIN BOARD)',
		'LISTED NBFC (CSE)',
		'LISTED NBFC (SME PLATFORM)',
		'UNLISTED PRIVATE NBFC COMPANY',
		'UNLISTED PUBLIC NBFC COMPANY',
	],
	'bse_main_board' => [
		'LISTED PUBLIC COMPANY (BSE MAIN BOARD)',
		'LISTED NBFC (BSE MAIN BOARD)',
	],
	'bse_main_board_group' => [
		'A', 'T', 'M', 'Z', 'B'
	],
 
	'acquisition_method' => [
		'Open Offer', 
		'Delisting Offer', 
		'Tender Offer', 
		'Market Purchase', 
		'Block/Bulk Deals', 
		'Preferential Allotment', 
		'Rights Issue', 
		'Mergers/Amalgamations', 
		'Private Agreement', 
		'Pledge Invocation', 
		'IBC Resolution', 
		'Others', 
	],
	'trading_conditions' => [
		'Active', 
		'ASM (Additional Surveillance Measure)', 
		'SMS (Special Margin Surveillance)', 
		'Non‐Compliance with SEBI Regulations', 
		'Trading Suspension', 
		'Penal Measures', 
		'Insolvency and Bankruptcy', 
		'Investigation or Regulatory Actions', 
		'Temporarily halted to facilitate corporate actions', 
		'Z Category Stocks', 
		'Restricted due to GSM (Graded Surveillance Measure)', 
		'Others',
	],
	'price_unit' => [
		'Rupees',
		'Thousand',
		'Lac',
		'Crore',
	],
	'listed_company' => [
		'LISTED PUBLIC COMPANY (NSE MAIN BOARD)', 
		'LISTED PUBLIC COMPANY (BSE MAIN BOARD)',
		'LISTED COMPANY (CSE)',
		'LISTED COMPANY (SME PLATFORM)',
		'LISTED NBFC (NSE MAIN BOARD)', 
		'LISTED NBFC (BSE MAIN BOARD)',
		'LISTED NBFC (CSE)',
		'LISTED NBFC (SME PLATFORM)',
	],
	'industry'=>[
		'Trading in goods', 
		'Chemicals used in agriculture, manufacturing, and science.',
		'Paints, varnishes, and colorants for industrial applications.', 
		'Industrial oils, lubricants, and fuels.',
		'Metals used in construction and manufacturing.',
		'Machines, machine tools, and engines.', 
		'Rubber, plastics, and insulating materials for industrial use.', 
		'Pharmaceuticals, veterinary preparations, and sanitary products.', 
		'Medical, dental equipment, and artificial limbs.', 
		'Veterinary services and products for animal health.', 
		'Beauty care services for humans and animals.', 
		'Agricultural chemicals and pesticides.', 
		'Meat, fish, dairy products, and preserved fruits.', 
		'Cereals, bakery products, and condiments.', 
		'Agricultural products, live animals, and animal food.', 
		'Non-alcoholic beverages, mineral waters, and fruit juices.', 
		'Alcoholic beverages including beer', 
		'Services related to agriculture, horticulture, and forestry.',
		'Cosmetics, soaps, and personal hygiene items.', 
		'Leather products, bags, and travel accessories.', 
		'Clothing, footwear, and headgear manufacturing.', 
		'Lace, embroidery, ribbons, and buttons.', 
		'Tobacco and smoking-related articles.', 
		'Metal-based construction materials.', 
		'Non-metallic materials like bricks, tiles, glass and other building materials', 
		'Services related to construction, repair, and maintenance.', 
		'Scientific and laboratory instruments and apparatus.', 
		'Electrical and electronic devices, including computers.', 
		'Design and development of software solutions.', 
		'Telecommunications services and equipment.', 
		'Manufacturing of vehicles and transport equipment.', 
		'Transport, logistics, packaging, and storage services.', 
		'Material treatment services like recycling or waste management.',
		'Apparatus for recording, transmission, and reproduction of sound and images.', 
		'Production and sale of musical instruments.', 
		'Education, training, and academic services.', 
		'Sporting, cultural, and entertainment-related services.', 
		'Advertising, marketing, and business management services.', 
		'Insurance, financial affairs, and real estate management.', 
		'Restaurants, catering, food and drink service management.', 
		'Hotels, inns, and temporary lodging facilities.', 
		'Law firms and legal consultation services.', 
		'Private security, surveillance, and personal protection services.', 
		'Manufacturing of furniture, home decor items.', 
		'Production of utensils, containers, cleaning and other household items.',
		'Textiles, Carpets, rugs, and wall hangings manufacturing.', 
		'Manufacture of sports equipment and accessories.', 
		'Production of toys, games, and recreational items.', 
		'Production of jewellery, precious metals, and horological instruments.',
		'High-end watches and luxury fashion accessories or other luxury and precious goods', 
		'Information Technology (Software / Technology)',
		'Solar / Renewable Energy',
		'NBFC / Microfinance / Financial Services',
		'Real Estate / Construction',
		'Gems & Jewellery',
		'Others', 
	],
	'roc'=> [
		'Ahmedabad', 
		'Andaman' ,
		'Bengaluru', 
		'Bilaspur', 
		'Chandigarh', 
		'Chennai', 
		'Coimbatore', 
		'Cuttack',
		'Daman & Diu', 
		'Delhi',
		'Ernakulam',
		'Guwahati', 
		'Gwalior', 
		'Haryana', 
		'Himachal', 
		'Hyderabad', 
		'Jaipur',
		'Jammu & Kashmir',
		'Kanpur', 
		'Kolkata', 
		'Mumbai', 
		'Panaji', 
		'Patna', 
		'Puducherry', 
		'Pune', 
		'Ranchi',
		'Shillong',
		'Uttarakhand', 
		'Vijaywada',
	],
	'type_of_entity' => [
		['NAME'=> 'ONE PERSON COMPANY (OPC)', 'SUFFIX' => 'OPC PRIVATE LIMITED'],
		['NAME'=> 'PRIVATE COMPANY', 'SUFFIX' => 'PRIVATE LIMITED'],
		['NAME'=> 'UNLISTED PUBLIC COMPANY' , 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'LISTED PUBLIC COMPANY (NSE MAIN BOARD)' , 'SUFFIX' => 'LIMITED'], 
		['NAME'=> 'LISTED PUBLIC COMPANY (BSE MAIN BOARD)' , 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'LISTED COMPANY (CSE)' , 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'LISTED COMPANY (SME PLATFORM)' , 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'LISTED NBFC (NSE MAIN BOARD)' ,'SUFFIX' => 'LIMITED'],
		['NAME'=> 'LISTED NBFC (BSE MAIN BOARD)' , 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'LISTED NBFC (CSE)', 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'LISTED NBFC (SME PLATFORM)', 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'UNLISTED PRIVATE NBFC COMPANY', 'SUFFIX' => 'PRIVATE LIMITED'],
		['NAME'=> 'UNLISTED PUBLIC NBFC COMPANY', 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'LIMITED LIABILITY PARTNERSHIP (LLP)', 'SUFFIX' => 'LLP'],
		['NAME'=> 'SECTION 8 COMPANY', 'SUFFIX' => 'FOUNDATION'],
		['NAME'=> 'PRODUCER PRIVATE COMPANY' , 'SUFFIX' => 'PRIVATE LIMITED'],
		['NAME'=> 'PRODUCER PUBLIC COMPANY', 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'NIDHI COMPANY', 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'IFSC PRIVATE COMPANY', 'SUFFIX' => 'PRIVATE LIMITED'],
		['NAME'=> 'IFSC PUBLIC COMPANY', 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'UNLIMITED PRIVATE COMPANY', 'SUFFIX' => 'PRIVATE LIMITED'],
		['NAME'=> 'UNLIMITED PUBLIC COMPANY', 'SUFFIX' => 'LIMITED'],
		['NAME'=> 'SECTION 8 MICRO FINANCE COMPANY', 'SUFFIX' => 'FOUNDATION'],
		['NAME'=> 'FOREIGN COMPANY', 'SUFFIX' => ''],
		

	],
	'type_of_entity_listed' => [
		'LISTED PUBLIC COMPANY (NSE MAIN BOARD)', 
		'LISTED PUBLIC COMPANY (BSE MAIN BOARD)',
		'LISTED COMPANY (CSE)',
		'LISTED COMPANY (SME PLATFORM)',
		'LISTED NBFC (NSE MAIN BOARD)', 
		'LISTED NBFC (BSE MAIN BOARD)',
		'LISTED NBFC (CSE)',
		'LISTED NBFC (SME PLATFORM)', 
		'LIMITED LIABILITY PARTNERSHIP (LLP)',



	],
	'type_of_entity_unlisted' => [
		'ONE PERSON COMPANY (OPC)',
		'PRIVATE COMPANY',
		'UNLISTED PUBLIC COMPANY',
		'UNLISTED PRIVATE NBFC COMPANY',
		'UNLISTED PUBLIC NBFC COMPANY',
		'SECTION 8 COMPANY',
		'PRODUCER PRIVATE COMPANY',
		'PRODUCER PUBLIC COMPANY',
		'NIDHI COMPANY',
		'IFSC PRIVATE COMPANY',
		'IFSC PUBLIC COMPANY',
		'UNLIMITED PRIVATE COMPANY',
		'UNLIMITED PUBLIC COMPANY'
		
	],
	'type_of_entity_llp' => [
		'LIMITED LIABILITY PARTNERSHIP (LLP)',
	],
	'type_of_entity_foriegn' => [
		'FOREIGN COMPANY',
	],
	
	 
	'property_type_option' => [
		"Physical"=>"Physical",
		"Virtual"=>"Virtual"
	],
	'ask_price_unit_option' => [
		"Rupees"=>"Rupees",
		"Thousand"=>"Thousand",
		"Lac"=>"Lac",
		"Crore"=>"Crore"
	],
	'states' => [
		"Andhra Pradesh"=>"Andhra Pradesh",
		"Andaman and Nicobar Islands"=>"Andaman and Nicobar Islands",
		"Arunachal Pradesh"=>"Arunachal Pradesh",
		"Assam"=>"Assam",
		"Bihar"=>"Bihar",
		"Chandigarh"=>"Chandigarh",
		"Chhattisgarh"=>"Chhattisgarh",
		"Dadar and Nagar Haveli"=>"Dadar and Nagar Haveli",
		"Daman and Diu"=>"Daman and Diu",
		"Delhi"=>"Delhi",
		"Lakshadweep"=>"Lakshadweep",
		"Puducherry"=>"Puducherry",
		"Goa"=>"Goa",
		"Gujarat"=>"Gujarat",
		"Haryana"=>"Haryana",
		"Himachal Pradesh"=>"Himachal Pradesh",
		"Jammu and Kashmir"=>"Jammu and Kashmir",
		"Jharkhand"=>"Jharkhand",
		"Karnataka"=>"Karnataka",
		"Kerala"=>"Kerala",
		"Madhya Pradesh"=>"Madhya Pradesh",
		"Maharashtra"=>"Maharashtra",
		"Manipur"=>"Manipur",
		"Meghalaya"=>"Meghalaya",
		"Mizoram"=>"Mizoram",
		"Nagaland"=>"Nagaland",
		"Odisha"=>"Odisha",
		"Punjab"=>"Punjab",
		"Rajasthan"=>"Rajasthan",
		"Sikkim"=>"Sikkim",
		"Tamil Nadu"=>"Tamil Nadu",
		"Telangana"=>"Telangana",
		"Tripura"=>"Tripura",
		"Uttar Pradesh"=>"Uttar Pradesh",
		"Uttarakhand"=>"Uttarakhand",
		"West Bengal"=>"West Bengal",

	],
];